{
    "openapi": "3.0.2",
    "info": {
     "title": "OpenSearch",
     "version": "2021-11-23"
    },
    "paths": {
     "/_search": {
      "post": {
       "description": "Returns results matching a query.",
       "operationId": "PostSearch",
       "requestBody": {
        "content": {
         "application/json": {
          "schema": {
           "$ref": "#/components/schemas/PostSearchRequestContent"
          },
          "examples": {
           "PostSearch_example1": {
            "summary": "Examples for Post Search Operation.",
            "description": "",
            "value": {
             "query": {
              "match_all": {}
             },
             "fields": [
              "*"
             ]
            }
           }
          }
         }
        }
       },
       "parameters": [
        {
         "name": "allow_no_indices",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "allow_partial_search_results",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "analyzer",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "analyze_wildcard",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "batched_reduce_size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "ccs_minimize_roundtrips",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "default_operator",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/DefaultOperator"
         }
        },
        {
         "name": "df",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "docvalue_fields",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "expand_wildcards",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/ExpandWildcards"
         }
        },
        {
         "name": "explain",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "from",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "ignore_throttled",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "ignore_unavailable",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "lenient",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "max_concurrent_shard_requests",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "pre_filter_shard_size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "preference",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "q",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "request_cache",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "rest_total_hits_as_int",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "routing",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "scroll",
         "in": "query",
         "schema": {
          "type": "string",
          "pattern": "^([0-9]+)(?:d|h|m|s|ms|micros|nanos)$"
         },
         "examples": {
          "PostSearch_example1": {
           "summary": "Examples for Post Search Operation.",
           "description": "",
           "value": "1d"
          }
         },
         "example": "1d"
        },
        {
         "name": "search_type",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/SearchType"
         }
        },
        {
         "name": "seq_no_primary_term",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "sort",
         "in": "query",
         "style": "form",
         "schema": {
          "type": "array",
          "items": {
           "type": "string"
          }
         },
         "explode": true
        },
        {
         "name": "source",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "source_excludes",
         "in": "query",
         "style": "form",
         "schema": {
          "type": "array",
          "items": {
           "type": "string"
          }
         },
         "explode": true
        },
        {
         "name": "source_includes",
         "in": "query",
         "style": "form",
         "schema": {
          "type": "array",
          "items": {
           "type": "string"
          }
         },
         "explode": true
        },
        {
         "name": "stats",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "stored_fields",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "suggest_field",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "suggest_mode",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/SuggestMode"
         }
        },
        {
         "name": "suggest_size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "suggest_text",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "terminate_after",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "timeout",
         "in": "query",
         "schema": {
          "type": "string",
          "pattern": "^([0-9]+)(?:d|h|m|s|ms|micros|nanos)$"
         }
        },
        {
         "name": "track_scores",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "track_total_hits",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "typed_keys",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "version",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        }
       ],
       "responses": {
        "200": {
         "description": "PostSearch 200 response",
         "content": {
          "application/json": {
           "schema": {
            "$ref": "#/components/schemas/PostSearchResponseContent"
           },
           "examples": {
            "PostSearch_example1": {
             "summary": "Examples for Post Search Operation.",
             "description": "",
             "value": {
              "timed_out": false,
              "_shards": {
               "total": 1,
               "successful": 1,
               "skipped": 0,
               "failed": 0
              },
              "hits": {
               "total": {
                "value": 0,
                "relation": "eq"
               },
               "hits": []
              }
             }
            }
           }
          }
         }
        }
       }
      }
     },
     "/{index}/_search": {
      "post": {
       "description": "Returns results matching a query.",
       "operationId": "PostSearchWithIndex",
       "requestBody": {
        "content": {
         "application/json": {
          "schema": {
           "$ref": "#/components/schemas/PostSearchWithIndexRequestContent"
          },
          "examples": {
           "PostSearchWithIndex_example1": {
            "summary": "Examples for Post Search With Index Operation.",
            "description": "",
            "value": {
             "query": {
              "match_all": {}
             },
             "fields": [
              "*"
             ]
            }
           }
          }
         }
        }
       },
       "parameters": [
        {
         "name": "index",
         "in": "path",
         "schema": {
          "type": "string",
          "pattern": "^[^+_\\-\\.][^\\\\, /*?\"<>| ,#\\nA-Z]+$"
         },
         "required": true,
         "examples": {
          "PostSearchWithIndex_example1": {
           "summary": "Examples for Post Search With Index Operation.",
           "description": "",
           "value": "books"
          }
         },
         "example": "books"
        },
        {
         "name": "allow_no_indices",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "allow_partial_search_results",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "analyzer",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "analyze_wildcard",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "batched_reduce_size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "ccs_minimize_roundtrips",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "default_operator",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/DefaultOperator"
         }
        },
        {
         "name": "df",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "docvalue_fields",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "expand_wildcards",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/ExpandWildcards"
         }
        },
        {
         "name": "explain",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "from",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "ignore_throttled",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "ignore_unavailable",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "lenient",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "max_concurrent_shard_requests",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "pre_filter_shard_size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "preference",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "q",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "request_cache",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "rest_total_hits_as_int",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "routing",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "scroll",
         "in": "query",
         "schema": {
          "type": "string",
          "pattern": "^([0-9]+)(?:d|h|m|s|ms|micros|nanos)$"
         },
         "examples": {
          "PostSearchWithIndex_example1": {
           "summary": "Examples for Post Search With Index Operation.",
           "description": "",
           "value": "1d"
          }
         },
         "example": "1d"
        },
        {
         "name": "search_type",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/SearchType"
         }
        },
        {
         "name": "seq_no_primary_term",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "sort",
         "in": "query",
         "style": "form",
         "schema": {
          "type": "array",
          "items": {
           "type": "string"
          }
         },
         "explode": true
        },
        {
         "name": "source",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "source_excludes",
         "in": "query",
         "style": "form",
         "schema": {
          "type": "array",
          "items": {
           "type": "string"
          }
         },
         "explode": true
        },
        {
         "name": "source_includes",
         "in": "query",
         "style": "form",
         "schema": {
          "type": "array",
          "items": {
           "type": "string"
          }
         },
         "explode": true
        },
        {
         "name": "stats",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "stored_fields",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "suggest_field",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "suggest_mode",
         "in": "query",
         "schema": {
          "$ref": "#/components/schemas/SuggestMode"
         }
        },
        {
         "name": "suggest_size",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "suggest_text",
         "in": "query",
         "schema": {
          "type": "string"
         }
        },
        {
         "name": "terminate_after",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "timeout",
         "in": "query",
         "schema": {
          "type": "string",
          "pattern": "^([0-9]+)(?:d|h|m|s|ms|micros|nanos)$"
         }
        },
        {
         "name": "track_scores",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "track_total_hits",
         "in": "query",
         "schema": {
          "type": "number"
         }
        },
        {
         "name": "typed_keys",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        },
        {
         "name": "version",
         "in": "query",
         "schema": {
          "type": "boolean"
         }
        }
       ],
       "responses": {
        "200": {
         "description": "PostSearchWithIndex 200 response",
         "content": {
          "application/json": {
           "schema": {
            "$ref": "#/components/schemas/PostSearchWithIndexResponseContent"
           },
           "examples": {
            "PostSearchWithIndex_example1": {
             "summary": "Examples for Post Search With Index Operation.",
             "description": "",
             "value": {
              "timed_out": false,
              "_shards": {
               "total": 1,
               "successful": 1,
               "skipped": 0,
               "failed": 0
              },
              "hits": {
               "total": {
                "value": 0,
                "relation": "eq"
               },
               "hits": []
              }
             }
            }
           }
          }
         }
        }
       }
      }
     }
    },
    "components": {
     "schemas": {
      "DefaultOperator": {
       "type": "string",
       "enum": [
        "AND",
        "OR"
       ]
      },
      "ExpandWildcards": {
       "type": "string",
       "enum": [
        "all",
        "open",
        "closed",
        "hidden",
        "none"
       ]
      },
      "Hits": {
       "type": "object",
       "properties": {
        "_index": {
         "type": "string"
        },
        "_type": {
         "type": "string"
        },
        "_id": {
         "type": "string"
        },
        "_score": {
         "type": "number",
         "format": "float"
        },
        "_source": {},
        "fields": {}
       }
      },
      "HitsMetadata": {
       "type": "object",
       "properties": {
        "total": {
         "$ref": "#/components/schemas/Total"
        },
        "max_score": {
         "type": "number",
         "format": "double"
        },
        "hits": {
         "type": "array",
         "items": {
          "$ref": "#/components/schemas/Hits"
         }
        }
       }
      },
      "PostSearchRequestContent": {
       "type": "object",
       "properties": {
        "docvalue_fields": {
         "type": "string"
        },
        "explain": {
         "type": "boolean"
        },
        "from": {
         "type": "number"
        },
        "seq_no_primary_term": {
         "type": "boolean"
        },
        "size": {
         "type": "number"
        },
        "source": {
         "type": "string"
        },
        "stats": {
         "type": "string"
        },
        "terminate_after": {
         "type": "number"
        },
        "timeout": {
         "type": "string",
         "pattern": "^([0-9]+)(?:d|h|m|s|ms|micros|nanos)$"
        },
        "version": {
         "type": "boolean"
        },
        "fields": {
         "type": "array",
         "items": {
          "type": "string"
         }
        },
        "min_score": {
         "type": "number"
        },
        "indices_boost": {
         "type": "array",
         "items": {}
        },
        "query": {
         "$ref": "#/components/schemas/UserDefinedObjectStructure"
        }
       }
      },
      "PostSearchResponseContent": {
       "type": "object",
       "properties": {
        "_scroll_id": {
         "type": "string"
        },
        "took": {
         "type": "number"
        },
        "timed_out": {
         "type": "boolean"
        },
        "_shards": {
         "$ref": "#/components/schemas/ShardStatistics"
        },
        "hits": {
         "$ref": "#/components/schemas/HitsMetadata"
        }
       },
       "example": {
        "timed_out": false,
        "_shards": {
         "total": 1,
         "successful": 1,
         "skipped": 0,
         "failed": 0
        },
        "hits": {
         "total": {
          "value": 0,
          "relation": "eq"
         },
         "hits": []
        }
       }
      },
      "PostSearchWithIndexRequestContent": {
       "type": "object",
       "properties": {
        "docvalue_fields": {
         "type": "string"
        },
        "explain": {
         "type": "boolean"
        },
        "from": {
         "type": "number"
        },
        "seq_no_primary_term": {
         "type": "boolean"
        },
        "size": {
         "type": "number"
        },
        "source": {
         "type": "string"
        },
        "stats": {
         "type": "string"
        },
        "terminate_after": {
         "type": "number"
        },
        "timeout": {
         "type": "string",
         "pattern": "^([0-9]+)(?:d|h|m|s|ms|micros|nanos)$"
        },
        "version": {
         "type": "boolean"
        },
        "fields": {
         "type": "array",
         "items": {
          "type": "string"
         }
        },
        "min_score": {
         "type": "number"
        },
        "indices_boost": {
         "type": "array",
         "items": {}
        },
        "query": {
         "$ref": "#/components/schemas/UserDefinedObjectStructure"
        }
       }
      },
      "PostSearchWithIndexResponseContent": {
       "type": "object",
       "properties": {
        "_scroll_id": {
         "type": "string"
        },
        "took": {
         "type": "number"
        },
        "timed_out": {
         "type": "boolean"
        },
        "_shards": {
         "$ref": "#/components/schemas/ShardStatistics"
        },
        "hits": {
         "$ref": "#/components/schemas/HitsMetadata"
        }
       },
       "example": {
        "timed_out": false,
        "_shards": {
         "total": 1,
         "successful": 1,
         "skipped": 0,
         "failed": 0
        },
        "hits": {
         "total": {
          "value": 0,
          "relation": "eq"
         },
         "hits": []
        }
       }
      },
      "Relation": {
       "type": "string",
       "enum": [
        "eq",
        "gte"
       ]
      },
      "SearchType": {
       "type": "string",
       "enum": [
        "0",
        "1"
       ]
      },
      "ShardStatistics": {
       "type": "object",
       "properties": {
        "total": {
         "type": "number"
        },
        "successful": {
         "type": "number"
        },
        "skipped": {
         "type": "number"
        },
        "failed": {
         "type": "number"
        }
       }
      },
      "SuggestMode": {
       "type": "string",
       "enum": [
        "0",
        "1",
        "2"
       ]
      },
      "Total": {
       "type": "object",
       "properties": {
        "value": {
         "type": "number"
        },
        "relation": {
         "$ref": "#/components/schemas/Relation"
        }
       }
      },
      "UserDefinedObjectStructure": {
       "type": "object",
       "properties": {
        "bool": {},
        "boosting": {},
        "combined_fields": {},
        "constant_score": {},
        "dis_max": {},
        "distance_feature": {},
        "exists": {},
        "function_score": {},
        "fuzzy": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "geo_bounding_box": {},
        "geo_distance": {},
        "geo_polygon": {},
        "geo_shape": {},
        "has_child": {},
        "has_parent": {},
        "ids": {},
        "intervals": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "knn": {},
        "match": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "match_all": {},
        "match_bool_prefix": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "match_none": {},
        "match_phrase": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "match_phrase_prefix": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "more_like_this": {},
        "multi_match": {},
        "nested": {},
        "parent_id": {},
        "percolate": {},
        "pinned": {},
        "prefix": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "query_string": {},
        "range": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "rank_feature": {},
        "regexp": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "script": {},
        "script_score": {},
        "shape": {},
        "simple_query_string": {},
        "span_containing": {},
        "field_masking_span": {},
        "span_first": {},
        "span_multi": {},
        "span_near": {},
        "span_not": {},
        "span_or": {},
        "span_term": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "span_within": {},
        "term": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "terms": {},
        "terms_set": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "wildcard": {
         "$ref": "#/components/schemas/UserDefinedValueMap"
        },
        "wrapper": {}
       }
      },
      "UserDefinedValueMap": {
       "type": "object",
       "additionalProperties": {}
      }
     },
     "securitySchemes": {
      "smithy.api.httpBasicAuth": {
       "type": "http",
       "description": "HTTP Basic authentication",
       "scheme": "Basic"
      }
     }
    },
    "security": [
     {
      "smithy.api.httpBasicAuth": []
     }
    ]
   }